Repository larq/zookeeper, pull requests merged in 2019-11, with the labels that each got.

#57 Upgrade black
  .github/workflows/lint.yml
Labels: internal-improvement

#58 Update .coveragerc
  .coveragerc
Labels: internal-improvement

#59 Minor preprocessing fix.
  zookeeper/preprocessing.py
Labels: bug

#60 Fix example and remove dataset repeat
  examples/larq_experiment.py
Labels: documentation

#62 Run tests on PRs.
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
Labels: internal-improvement

#61 Add support for builder configs to `Dataset`.
  zookeeper/dataset.py
Labels: internal-improvement

#63 Make `Dataset` abstract and support a `MultiTFDSDataset`.
  examples/larq_experiment.py
  zookeeper/__init__.py
  zookeeper/dataset.py
Labels: feature

#64 Revert "Remove dataset repeat to simplify example"
  examples/larq_experiment.py
Labels: documentation

#67 Support TFDS S3 dataset splits.
  zookeeper/dataset.py
Labels: internal-improvement

#70 Fix `AttributeError` false-positive.
  zookeeper/component.py
Labels: bug

#69 Throw more meaningful AttributeError
  zookeeper/component.py
Labels: internal-improvement

#65 Improve linting.
  .github/workflows/lint.yml
  .gitignore
  setup.cfg
  setup.py
  zookeeper/__init__.py
  zookeeper/cli.py
  zookeeper/component.py
  zookeeper/component_test.py
  zookeeper/dataset.py
  zookeeper/experiment.py
  zookeeper/model.py
  zookeeper/preprocessing.py
  zookeeper/task.py
  zookeeper/task_test.py
  zookeeper/utils.py
Labels: internal-improvement

#71 Allow paths to be passed through the CLI, and add CLI tests.
  zookeeper/cli.py
  zookeeper/cli_test.py
  zookeeper/utils.py
Labels: bug

#73 Close type-checking loophole. Closes #68.
  zookeeper/cli_test.py
  zookeeper/component.py
  zookeeper/component_test.py
  zookeeper/utils.py
Labels: bug

#79 Tidy-up error messages.
  zookeeper/component.py
Labels: internal-improvement

#80 Configure only the top-level reference to a component. Closes #72.
  zookeeper/component.py
  zookeeper/component_test.py
Labels: bug

#81 Fix bug in `num_examples` of `MultiTFDSDataset`.
  zookeeper/dataset.py
Labels: bug

#82 Fix bug with sub-component naming.
  zookeeper/component.py
Labels: bug
