Repository larq/zookeeper, pull requests merged in 2020-02, with the labels that each got.

#109 Make component fields explicit
  README.md
  examples/larq_experiment.py
  setup.py
  zookeeper/__init__.py
  zookeeper/core/__init__.py
  zookeeper/core/cli_test.py
  zookeeper/core/component.py
  zookeeper/core/component_test.py
  zookeeper/core/field.py
  zookeeper/core/field_test.py
  zookeeper/core/partial_component.py
  zookeeper/core/partial_component_test.py
  zookeeper/core/task.py
  zookeeper/core/task_test.py
  zookeeper/core/utils.py
  zookeeper/tf/dataset.py
  zookeeper/tf/experiment.py
  zookeeper/tf/preprocessing.py
Labels: breaking-change

#112 Allow `ComponentField`s to be optional.
  zookeeper/core/component_test.py
  zookeeper/core/field.py
  zookeeper/core/field_test.py
Labels: feature

#110 Support `@factory` components
  .github/workflows/unittest.yml
  examples/larq_experiment.py
  zookeeper/__init__.py
  zookeeper/core/__init__.py
  zookeeper/core/cli_test.py
  zookeeper/core/component.py
  zookeeper/core/component_test.py
  zookeeper/core/factory.py
  zookeeper/core/factory_registry.py
  zookeeper/core/factory_test.py
  zookeeper/core/field.py
  zookeeper/core/task.py
  zookeeper/core/utils.py
  zookeeper/core/utils_test.py
  zookeeper/tf/__init__.py
  zookeeper/tf/experiment.py
  zookeeper/tf/model.py
Labels: feature

#114 Add a post-configure hook for components. Closes #89.
  zookeeper/core/component.py
  zookeeper/core/component_test.py
Labels: feature

#113 Raise an error if a component is configured with an unknown key.
  zookeeper/core/cli_test.py
  zookeeper/core/component.py
  zookeeper/core/component_test.py
Labels: feature

#115 Add `allow_missing` as a flag to `Field`s and `ComponentField`s.
  zookeeper/core/component.py
  zookeeper/core/component_test.py
  zookeeper/core/field.py
  zookeeper/core/field_test.py
Labels: feature

#116 Add extra test for `allow_missing` fields.
  zookeeper/core/component_test.py
Labels: internal-improvement

#118 Fix error when printing components with `allow_missing` fields.
  zookeeper/core/component.py
  zookeeper/core/component_test.py
Labels: bug

#120 Fix config scoping, some comment changes
  zookeeper/core/component.py
Labels: bug

#119 Extend component example
  zookeeper/core/component.py
Labels: documentation

#122 Check for field name before implicitly calling `build()`. Closes #121.
  zookeeper/core/component.py
  zookeeper/core/component_test.py
Labels: bug

#125 Disable dataset downloading by default.
  .github/workflows/unittest.yml
  zookeeper/tf/dataset.py
Labels: feature

#124 Don't recursively configure non-component instance. Closes #123.
  zookeeper/core/component.py
  zookeeper/core/component_test.py
Labels: bug
