Repository larq/zookeeper, pull requests merged in 2020-12, with the labels that each got.

#209 Fix _list_field_strings
  zookeeper/core/component.py
Labels: internal-improvement

#212 :arrow_up: 1.0.6
  setup.py
Labels: skip-changelog

#211 Allow 'setattr' on unconfigured fields
  zookeeper/core/component.py
  zookeeper/core/component_test.py
Labels: feature

#213 Fix usage of `setattr` in complex scenarios with nested components.
  zookeeper/core/component.py
  zookeeper/core/component_test.py
Labels: internal-improvement

#214 Add TF 2.4 to CI matrix
  .github/workflows/unittest.yml
Labels: internal-improvement

#210 Add __configure__ function to component
  zookeeper/core/component.py
  zookeeper/core/component_test.py
  zookeeper/core/factory.py
  zookeeper/core/factory_registry.py
  zookeeper/core/field.py
  zookeeper/core/partial_component.py
  zookeeper/core/task.py
  zookeeper/core/task_test.py
  zookeeper/core/utils.py
  zookeeper/tf/dataset.py
  zookeeper/tf/experiment.py
  zookeeper/tf/preprocessing.py
Labels: feature

#217 :arrow_up: 1.1.0
  setup.py
Labels: skip-changelog
