Repository larq/zookeeper, pull requests merged in 2020-01, with the labels that each got.

#90 Fix tfds import
  zookeeper/tf/preprocessing.py
Labels: bug

#91 Change component colouring in __repr__
  zookeeper/core/component.py
  zookeeper/core/component_test.py
Labels: internal-improvement

#93 Allow snake-case-normalised command aliases.
  zookeeper/core/cli.py
  zookeeper/core/cli_test.py
  zookeeper/core/task.py
  zookeeper/core/utils.py
Labels: feature

#94 Fix preprocessing decoders type
  zookeeper/tf/preprocessing.py
Labels: bug

#96 Add flag syntax for setting boolean params through the CLI. Closes #76.
  zookeeper/core/cli.py
  zookeeper/core/cli_test.py
  zookeeper/core/task.py
Labels: feature

#95 Fix example and add test to prevent future problems.
  .github/workflows/unittest.yml
  examples/larq_experiment.py
Labels: bug

#97 Simplify example
  examples/larq_experiment.py
Labels: documentation

#98 Rename MultiTFDSDataset.train_splits :arrow_right: train_split, suppo…
  zookeeper/core/component_test.py
  zookeeper/core/task_test.py
  zookeeper/tf/dataset.py
  zookeeper/tf/preprocessing.py
Labels: breaking-change

#100 Add help message for interactive mode
  zookeeper/core/task.py
Labels: documentation

#104 Rename BinaryNetCifar10 --> BinaryNetMnist
  .github/workflows/unittest.yml
  README.md
  examples/larq_experiment.py
Labels: internal-improvement

#107 Remove metrics, learning_rate_schedule and callbacks from experiment class
  .github/workflows/unittest.yml
  examples/larq_experiment.py
  zookeeper/tf/experiment.py
Labels: breaking-change

#108 Add more TF versions on CI
  .github/workflows/unittest.yml
Labels: internal-improvement
