Repository larq/zookeeper, pull requests merged in 2020-05, with the labels that each got.

#142 Fix split API usage for recent versions of TFDS.
  zookeeper/tf/dataset.py
Labels: bug

#141 Remove `prompt-toolkit` as a dependency, and use `click` instead.
  setup.py
  zookeeper/core/component_test.py
  zookeeper/core/utils.py
Labels: dependencies

#143 :arrow_up: v1.0.1
  setup.py
Labels: internal-improvement

#145 Option for Sequence of losses (for models with multiple outputs)
  zookeeper/tf/experiment.py
Labels: internal-improvement

#146 Increment version number
  setup.py
Labels: internal-improvement
