Repository larq/zookeeper, pull requests merged in 2021-02, with the labels that each got.

#224 Update TF package versions on CI.
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
Labels: internal-improvement

#223 Add ConfigurationError and base_hasattr
  zookeeper/core/component.py
  zookeeper/core/component_test.py
  zookeeper/core/field.py
  zookeeper/core/field_test.py
  zookeeper/core/utils.py
Labels: internal-improvement

#227 Perform component configuration in a breadth-first order.
  zookeeper/core/component.py
  zookeeper/core/component_test.py
  zookeeper/core/task.py
Labels: bug

#228 Ensure the component parent attribute is set correctly. Closes #225.
  zookeeper/core/component.py
  zookeeper/core/component_test.py
Labels: bug

#230 :arrow_up: v1.2.0
  setup.py
Labels: skip-changelog
